name: conda_ma_wagner
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.2=py37hadc3359_0
  - pywavelets=1.1.1=py37he774522_2
  - python=3.7.9=h60c2a47_0
  - matplotlib=3.3.2=0
  - seaborn=0.11.0=py_0
  - tensorflow=2.1.0=eigen_py37hd727fc0_0
  - tensorflow-base=2.1.0=eigen_py37h49b2757_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - scikit-learn=0.23.2=py37h47e9c7a_0
  - scipy=1.5.2=py37h9439919_0
  - joblib=0.17.0=py_0
  - pandas=1.1.3=py37ha925a31_0
  - more-itertools=8.6.0=pyhd3eb1b0_0
  - pip=20.2.4=py37haa95532_0
  - pip:
    - keras==2.3.1
    - tsfresh==0.17.0
    - opencv-python==4.1.1.26
    - pmdarima==1.8.0
  